### ISSUE TITLE
Unable to compile, Maven file location changed

### ISSUE THREAD

**Issue by redbarron-gcp** [GoogleCloudPlatform/container-developer-workshop#28]
The file location has been changed so we are unable to compile without manually editing the [maven-wrapper.properties] file. (https://github.com/GoogleCloudPlatform/container-developer-workshop/blob/93bf21a7d78cc9972f02256a887ade662d1c40b7/sample-apps/java/hello-world-maven/.mvn/wrapper/maven-wrapper.properties)

**Comment by arueth** [comment]
Resolved by https://github.com/GoogleCloudPlatform/container-developer-workshop/commit/36fb574f75a4aee90a1731c587af1e56d87982b1
